### ISSUE TITLE
Raffle Meter: Pretty on the page

### ISSUE THREAD

**Issue by gisellegk** [team178/team178.github.io#36]
__Available mentors:__ Giselle Koo
(feel free to add yourself)
**Progress:**
- [X] Center it
- [X] Make it not tiny on big displays
- [X] Make it not extend too far on mobile
- [X] Add more info
- [X] Fix the margins
- [X] Debug everything!
- [X] Pick proper colors (#43)
- [ ] Make it look right in IE (#38)
- [x] Make the drop-downs not go behind the small meter (#50/#58)

![screenshot from 2015-11-18 13 37 21](https://cloud.githubusercontent.com/assets/3026367/11250245/8802e0d0-8df9-11e5-82ab-71da88f8b075.png)

How can we make this look better? What information should we display, aside from % sold, and how do we want to display it?

**Comment by TJScalzo** [comment]
I will look into making the font size based on a percentage or something so it is more responsive.

**Comment by gisellegk** [comment]
#39 helps with this -- tool tips to display more details!

Raffle Progress Bar
(Mouse over the logo for details.) (smaller text)
ENFORCERS
Tickets Sold: 6% of goal | Click here to learn about the raffle >>

**Comment by gisellegk** [comment]
We should also add how many days left until the raffle drawing

**Comment by TJScalzo** [comment]
An

**Comment by TJScalzo** [comment]
![image](https://cloud.githubusercontent.com/assets/15825214/11301641/bc2be9d8-8f66-11e5-9d6e-2d626eb8ac38.jpeg)
 This *should* get fixed when I add in responsive text height. However, I feel like we're going to run into issues anyway.

**Comment by gluxon** [comment]
So one method to tackle the raffle meter responsiveness would be to use [viewport-percentage lengths](https://developer.mozilla.org/en-US/docs/Web/CSS/length#Viewport-percentage_lengths). I was able to use the `vw` unit make the meter scale with my browser window and mobile friendly as a result.

@TJScalzo Explore the vw unit a little and see what you can come up with. I have my solution on my computer, but what fun would it be to just give you my source? :P Have fun learning, and don't be afraid to ask if you get stuck.

**Comment by TJScalzo** [comment]
**Announcement:** Issues #43 and #51 could be considered to be nested under this one. (And if not #43 then at least the spirit of it.)

**Comment by TJScalzo** [comment]
I will try to create a better color theme thing to use for the website that better matches what the "official" colors are.

**Comment by TJScalzo** [comment]
In the small raffle meter, the background of the percent div is white with 50% opacity. Is this really necessary? 
![screen shot 2015-11-28 at 1 34 42 pm](https://cloud.githubusercontent.com/assets/15825214/11453335/d6a67a7a-95d4-11e5-9c1d-bef5b1f2e485.png)
Unless there's a specific reason why the background is like this, I don't think it needs to be like that.
![screen shot 2015-11-28 at 1 36 54 pm](https://cloud.githubusercontent.com/assets/15825214/11453347/22350c36-95d5-11e5-8901-eee3544c9087.png)
I'm not really sure which is better; I just think the fact that there are two different yellows is a little colors.

**Comment by gisellegk** [comment]
In the *achem* completely NOT theoretical future possibility *achem* where the blue area extends behind the text, it is difficult to read. That's the only reason why the white background is there.

**Comment by gisellegk** [comment]
I was toying with making the meter bar taller and vertically centering the `<span>`, so that there's a border of normal color around the top and bottom... but I couldn't get it right so I figured this was good enough to ship for today

**Comment by TJScalzo** [comment]
The only thing that needs to be fixed in here is IE and that has its own issue (#38). See #60 for any other things that need to be fixed.
